export interface Artisan {
    name: string,
    address: string,
    bday: Date,
    phone: number,
    email: string,
    password: string,
    confirmPassword: string,
    selfie: string,
    primaryIdPic: string,
    primaryIdNum: string,
    nbi: string,
    applyJob: string,
    tutorFile: string,
    nannyFile: string,
    housekeepingFile: string,
    haircutMassageFile: string,
    picture: string,
    id_image: string,
    id_number: number
}